## Constraints validator

In [40]:


result = [True, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, True, True, True, False, False, False, False, True, True, False, False, False, False, False, False, False, True, True, False, False, False, False, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, False, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, False, False, False, False, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, False, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, True, True, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, True, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, False, True, True, True, False, False, True, True, True, True, False, False, True, True, True, True, True, True, True, False, False, False, False, True, True, True, True, False, False, False, True, True, True, True, False, False, False, True, True, True, True, True, True, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, False, False, False, False, False, False, True, True, False, False, False, False, False] 
result = np.array(result)
result = result.reshape((6, -1))

# for i in range(result.shape[1]):
#     if np.all(result[:,i] == True):
#         print("hey")
result

array([[ True, False, False, False, False, False, False,  True,  True,
        False, False, False, False, False, False, False,  True,  True,
        False, False, False, False,  True,  True, False, False, False,
        False, False, False, False,  True,  True, False, False, False,
        False, False, False,  True,  True,  True, False, False, False,
        False,  True,  True, False, False, False, False, False, False,
        False,  True,  True, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True, False, False, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False, False, False],
    

In [25]:
import numpy as np

# Input:
path = "data\\Example"

# TODO - Set the Instance number, and give the results of your experiment
exNum = 7
result = [2, 2, 3, 3, 3, 3, 3, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 3, 3, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0] 
o = 0

groups, numShifts, demand, minShift, maxShift, minOff, maxOff, minOn, maxOn, forbidden, forbidden3 = readExample(exNum)

preview()

validate()

Example 7 :
groups:  29
numShifts:  3
demand:  [[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
minShift:  [2, 2, 2]
maxShift:  [7, 6, 5]
minOff:  2
maxOff:  4
minOn:  4
maxOn:  7
forbidden:  {2: [1], 3: [1, 2]}
forbidden3:  []
Everything's well.


## Assertions

In [2]:
def validate():
    # Assert that demand matrix is satisfied
    eq1_2()
    # Assert that symmetry constraints are satisfied
    eq3_4()
    # Assert that maximum and minimum shift constraints are satisfied
    eq5_6()
    # Assert that maximum and minimum consecutive working days are satisfied
    eq7_8()
    # Assert that fobidden constraints are satisfied
    eq9()
    eq10()
    # Assert that offset constraint is satisfied
    eq11()
    print("Everything's well.")

## Preparatory scripts

In [3]:
def readExample(exNum, path="data\\Example"):
    f = open(path + str(exNum) + ".dzn", "r").read().split(";")
    groups = int(f[0].split(" ")[-1])
    numShifts = int(f[1].split(" ")[-1])

    demand = []
    string2 = f[2].split("=")[1].split("|")[1:][:-1]
    for s in string2:
        try:
            demand.append(list(map(int, s.split("\n")[0][:-1].split(","))))
        except:
            demand.append(list(map(int, s.split("\n")[0].split(","))))
    demand = np.stack(demand) 


    minShift = list(map(int, f[3].split("=")[-1][2:-1].split(",")))
    maxShift = list(map(int, f[4].split("=")[-1][2:-1].split(",")))
    minOff = int(f[5].split(" ")[-1])
    maxOff = int(f[6].split(" ")[-1])
    minOn = int(f[7].split(" ")[-1])
    maxOn = int(f[8].split(" ")[-1])

    forb = " ".join(f[9].split(" ")[2:])[1:-1].split("{")[1:]
    forbidden = {}
    for idx,val in enumerate(forb):
        try:
            forbidden[idx+1] = list(map(int, val.split("}")[0].split(",")))
        except: 
            continue

    forbidden3 = []
    string2 = f[10].split("=")[1].split("|")[1:][:-1]
    if not string2[0].isspace():    
        for s in string2:
            try:
                forbidden3.append(list(map(int, s.split("\n")[0][:-1].split(","))))
            except:
                forbidden3.append(list(map(int, s.split("\n")[0].split(","))))
        forbidden3 = np.stack(forbidden3) 
    return groups, numShifts, demand, minShift, maxShift, minOff, maxOff, minOn, maxOn, forbidden, forbidden3

In [4]:
def preview():
    print("Example", exNum, ":")
#     print("\n")
    print("groups: ", groups)
    print("numShifts: ", numShifts)
    print("demand: ", demand)
    print("minShift: ", minShift)
    print("maxShift: ", maxShift)
    print("minOff: ", minOff)
    print("maxOff: ", maxOff)
    print("minOn: ", minOn)
    print("maxOn: ", maxOn)
    print("forbidden: ", forbidden)
    print("forbidden3: ", forbidden3)
    print("=======================================================")

## Equations 1, 2

In [5]:
def eq1_2():

    res_res = np.reshape(result, [-1, 7])
    for w in range(7):
        for i in range(1, numShifts+1):
            assert demand[i-1, (w + o) % 7] == np.sum(res_res[:, w] == i)
        assert np.sum(demand[:, (w + o) % 7]) == np.sum(res_res[:, w] != 0)
    


## Equations 3,4

In [6]:
def eq3_4():
    assert result[0] != 0
    assert result[-1] == 0

## Equations 5,6

In [7]:
# Check max-min consecutive shifts (equations 5,6)
def CheckShifts(num, result):
    max_counter = -1
    min_counter = len(result) + 1

    counter = 0
    for res in result:
        if res == num:
            counter += 1
        elif counter > 0:
            if counter > max_counter:
                max_counter = counter
            if counter < min_counter:
                min_counter = counter
            counter = 0
    if counter > 0:
        if counter > max_counter:
            max_counter = counter
        if counter < min_counter:
            min_counter = counter
        counter = 0
        
    return min_counter, max_counter

def eq5_6():
    # Check shifts
    shifts = range(1, numShifts+1)

    for num in shifts:

        min_counter, max_counter = CheckShifts(num, result)
        if min_counter < minShift[num-1]:
            print("ERROR MinShift constraints for shift", num)
            print(min_counter, minShift[num-1])
        if max_counter > maxShift[num-1]:
            print("ERROR MaxShift constraints for shift", num)

    # Check off-day
    min_counter, max_counter = CheckShifts(0, result)

    if min_counter < minOff:
        print("ERROR MinShift constraints for off day")
        print(min_counter, minShift[num-1])
    if max_counter > maxOff:
        print("ERROR MaxShift constraints for off day")

## Equations 7,8

In [8]:
# Check consecutive days with no day-off: (equations 7,8)
def checkWorkDays(result):
    max_counter = -1
    min_counter = len(result) + 1

    counter = 0
    for res in result:
        if res != 0:
            counter += 1
        elif counter > 0:
            if counter > max_counter:
                max_counter = counter
            if counter < min_counter:
                min_counter = counter
            counter = 0
    if counter > 0:
        if counter > max_counter:
            max_counter = counter
        if counter < min_counter:
            min_counter = counter
        counter = 0
        
    return min_counter, max_counter

def eq7_8():
    min_counter, max_counter = checkWorkDays(result)
    if min_counter < minOn:
        print("ERROR MinOn constraint")
        print(min_counter, minOn)
    if max_counter > maxOn:
        print("ERROR MaxOn constraint")
        print(max_counter, maxOn)

## Equations 9,10

In [9]:
# Testing equations 9,10
def eq9():
    for s in range(1, numShifts+1):
        if s in forbidden.keys():
            for idx in range(len(result)-1):
                if result[idx] == s:
                    assert result[idx+1] not in forbidden[s] 
    
def eq10():
    res_ravelled = result + result
#     import pdb; pdb.set_trace()
    for row in forbidden3:
        for i in range(len(result)):
            assert not np.all(res_ravelled[i:i+len(row)] == row)


## Equations 11

In [10]:
# Testing eq 11 
def eq11():
    demand_sum = np.sum(demand, axis=0)
#     import pdb;pdb.set_trace()
    o_expected = np.where(demand_sum[1:] - np.roll(demand_sum, 1)[1:]>0)[0]
    if len(o_expected) > 0:
        assert o == o_expected[0] + 1
    else:
        assert o == 0